### PR TITLE
Improve video encoding settings

### PR DESCRIPTION
**Pull request by maxdudik**
**Problem**
Current video encoding settings are not optimal for file size, especially for such content as storyboards, playblasts and renders with low in-frame activity.

**Solution**
Change ffmpeg's rate control mode to Constant Rate Factor instead of Constant Bitrate.

I've tested several ffmpeg options on various types of content and found that CRF value of 15 gives pretty identical quality and reduces overall size almost twice.

### CODE REVIEW

**Comment by frankrousseau** [comment]
Hello,
Thank you for this PR. Can you still build playlist with this setting?

**Comment by maxdudik** [comment]
Hi. We are not using playlist feature yet, so i can't say

**Comment by maxdudik** [comment]
Now tested on my dev deployment and it works

**Comment by frankrousseau** [comment]
Ok. We have to make tests on our side. It could lead to a lot of problems. So we want to be sure it works as expected.

**Comment by frankrousseau** [comment]
I did some tests. The videos look similar. Let's try!

**Pull request merged**
